create table AUTHORITY_ROLE
(
    ID       VARCHAR2(32) default SYS_GUID() not null
        primary key,
    ROLENAME VARCHAR2(50),
    ROLEDESC VARCHAR2(50)
)
/

comment on table AUTHORITY_ROLE is '角色表'
/

comment on column AUTHORITY_ROLE.ID is '主键uuid'
/

comment on column AUTHORITY_ROLE.ROLENAME is '角色名'
/

comment on column AUTHORITY_ROLE.ROLEDESC is '角色描述'
/

INSERT INTO STUDY57.AUTHORITY_ROLE (ID, ROLENAME, ROLEDESC) VALUES ('2E6AC18FDD9E42F69D21020EC28DF5E8', 'ROLE_ADMIN', '管理员用户');
INSERT INTO STUDY57.AUTHORITY_ROLE (ID, ROLENAME, ROLEDESC) VALUES ('560F399D843E4BA98499D958F3FBA2CB', 'ROLE_USER', '普通用户');
INSERT INTO STUDY57.AUTHORITY_ROLE (ID, ROLENAME, ROLEDESC) VALUES ('1CB4B06B80314F229CDA1E1EDDF17886', 'ROLE_GUEST', '访客角色');