create table AUTHORITY_PERMISSION
(
    ID             VARCHAR2(32) default SYS_GUID() not null
        primary key,
    PERMISSIONNAME VARCHAR2(50),
    URL            VARCHAR2(50)
)
/

comment on table AUTHORITY_PERMISSION is '资源权限表'
/

comment on column AUTHORITY_PERMISSION.ID is '主键uuid'
/

comment on column AUTHORITY_PERMISSION.PERMISSIONNAME is '权限名'
/

comment on column AUTHORITY_PERMISSION.URL is '资源路径'
/

INSERT INTO STUDY57.AUTHORITY_PERMISSION (ID, PERMISSIONNAME, URL) VALUES ('C9D7DB41638F4ED1B775E028F1A34BCF', 'role save', '/role/save');
INSERT INTO STUDY57.AUTHORITY_PERMISSION (ID, PERMISSIONNAME, URL) VALUES ('C03ABD1FF7044D8C84F3552D851D3F45', 'role findAll', '/role/findAll');
INSERT INTO STUDY57.AUTHORITY_PERMISSION (ID, PERMISSIONNAME, URL) VALUES ('6668AFED92C14F46ABF558E83A47BC2E', 'user findAll', '/user/findAll');
INSERT INTO STUDY57.AUTHORITY_PERMISSION (ID, PERMISSIONNAME, URL) VALUES ('934C68A0975345DF8EC972B3C4DD9A73', 'user findById', '/user/findById');